sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t juniorbezerra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true juniorbezerra/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "pipeline-react"
  env: "Pipelinereact-env"
  bucket_name: "elasticbeanstalk-us-east-2-861493268032"
  bucket_path: "pipeline-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY