sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t juniorbezerra/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true juniorbezerra/docker-react npm run test
